edition = "2024"
style_edition = "2024"

condense_wildcard_suffixes = true
empty_item_single_line = true
fn_call_width = 80
fn_params_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
newline_style = "Unix"
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
use_small_heuristics = "Max"
