[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
links = "vgmstream"
name = "vgmstream-sys"
repository.workspace = true
version = "0.1.0-vgmstream-r1980-16-g1f3a6b36"

[build-dependencies]
bindgen = "0.71.1"
cmake = "0.1.53"

[features]
default = []
atrac9 = []
celt = []
ffmpeg = []
g719 = []
g7221 = []
mpeg = []
speex = []
static = []
vorbis = []
