[package]
name = "vgmstream"
version = "0.2.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bitflags = "2.9.1"
thiserror = "2.0.14"
vgmstream-sys = { path = "../vgmstream-sys" }
