[package]
name = "vgmstream"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = "2.0.11"
vgmstream-sys = { path = "../vgmstream-sys" }
