name: Fmt

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Fmt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Install nasm
        uses: ilammy/setup-nasm@v1

      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: cargo fmt --all -- --check
