name: Lint

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install FFmpeg
        id: setup-ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3.1
        with:
          ffmpeg-version: "7.1"
          linking-type: shared

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install nasm
        uses: ilammy/setup-nasm@v1

      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: |
          export FFMPEG_DIR='${{ steps.setup-ffmpeg.outputs.ffmpeg-path }}'
          cargo clippy -- -D warnings
