name: Lint

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install nasm
        uses: ilammy/setup-nasm@v1

      - uses: Swatinem/rust-cache@v2

      - name: Lint
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings
