name: Test

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install nasm
        uses: ilammy/setup-nasm@v1

      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: cargo test
